name: Php-stan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  php-stan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - uses: php-actions/composer@v6

      - name: Running Code Style
        run: ./vendor/bin/phpstan analyse
