name: Style

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bare_run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: 8.2

    steps:
      -   uses: actions/checkout@v3

      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      -   run: mkdir nested-dir

      -   run: composer require symplify/easy-coding-standard --dev --ansi
          working-directory: nested-dir

      -   run: vendor/bin/ecs list --ansi
          working-directory: nested-dir
