branches: [ "master" ]

jobs:
  styling:
    runs-on: ubuntu-latest
steps:
  - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    with:
      php-version: '8.2'
  - uses: actions/checkout@v4
  - name: Copy .env
    run: php -r "file_exists('.env') || copy('.env.example', '.env');"
  - name: Install Dependencies
    run: composer install
  - name: Run code style
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    run: vendor/bin/ecs --fix
