name: Code style
on:
  push:
  workflow_dispatch:

jobs:
  code-style:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: exif
          tools: composer:v2

      - uses: actions/checkout@v3
        with:
          # Ensure the branch is checked out so changes can be pushed
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Running Code Style
        run: ./vendor/bin/ecs --fix

      - uses: EndBug/add-and-commit@v9
        with:
          message: Updating files
          committer_name: GitHub Actions
          committer_email: actions@github.com
