name: Style

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  strategy:
    fail-fast: false
    matrix:
      actions:
        - name: 'Coding Standard'
          run: composer fix-cs --ansi

  name: ${{ matrix.actions.name }}
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        coverage: none

    - uses: "ramsey/composer-install@v2"
    - run: ${{ matrix.actions.run }}
