name: Style PHP-CS-Fixer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Install composer packages
        run: composer install

#      - name: Configure Git
#        run: |
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "github-actions[bot]@users.no.reply.github.com"

      - name: Run ECS
        run: ./vendor/bin/ecs --fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply PHP-CS-Fixer changes
