name: PHP Code style
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  CS:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # Ensure the branch is checked out so changes can be pushed
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: php-actions/composer@v6
      - with:
          php-version: '8.4'

      - name: Running Code Style
        run: ./vendor/bin/ecs --fix

      - uses: EndBug/add-and-commit@v9
        with:
          message: Updating files
          committer_name: GitHub Actions
          committer_email: actions@github.com
